language: c++

matrix:
  include:

    - os: linux
      env: BUILD_TYPE="vanilla"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Release"
           CTEST_OPTIONS="--output-on-failure -j2"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="asan"
           CFLAGS="-fsanitize=address"
           CXXFLAGS="-fsanitize=address"
           LDFLAGS="-fsanitize=address"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Debug"
           CTEST_OPTIONS="--output-on-failure -j2"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="lsan"
           CFLAGS="-fsanitize=leak"
           CXXFLAGS="-fsanitize=leak"
           LDFLAGS="-fsanitize=leak"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Debug"
           CTEST_OPTIONS="--output-on-failure -j2"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="ubsan"
           CFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           CXXFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           LDFLAGS="-fsanitize=undefined"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Debug"
           CTEST_OPTIONS="--output-on-failure -j2"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="libc++-n-clang"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Release"
           CTEST_OPTIONS="--output-on-failure -j2"
           CXXFLAGS="-stdlib=libc++"
           MK_CC=clang
           MK_CXX=clang++
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="coverage"
           CFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           CMAKE_BUILD_OPTIONS="-v"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Debug"
           CTEST_OPTIONS="--output-on-failure -j2"
           CXXFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           LDFLAGS="-lgcov"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required
